defaults: &defaults
  host: localhost
  slaves:
      - host: slave1.local
        port: 27017
#      - host: slave2.local
#        port: 27019
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: false

development:
  <<: *defaults
  database: nodes_dev

test:
  <<: *defaults
  database: nodes_dev

production:
  <<: *defaults
  database: nodes_prod
